name: CI

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20.x'

      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --tests=false
          skip-pkg-cache: true
          skip-go-installation: true

      - name: Run tests
        run: make test-with-junit-report

      - name: Junit report
        uses: test-summary/action@v1
        if: ${{ success() || failure() }}
        with:
          paths: 'test-results/tests.xml'
