name: Force build & publish

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: "Set docker version manually"
        required: true
        default: ""

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ziollek/cb-tracker:${{ steps.tag_version.outputs.version }}
          file: docker/Dockerfile